#include "uchat-client.h"

const char *jokes[] = {
    "Why don't skeletons fight each other? They don't have the guts!",
    "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call fake spaghetti? An impasta!",
    "Why did the math book look sad? Because it had too many problems.",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you get when you cross a snowman with a vampire? Frostbite!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "How does a penguin build its house? Igloos it together!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "What did the fish say when it hit the wall? Dam!",
    "Why did the coffee file a police report? It got mugged!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "What did one hat say to the other? You stay here, I'll go on ahead!",
    "Why don't skeletons fight each other? They don't have the guts!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did one ocean say to the other ocean? Nothing, they just waved!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What's orange and sounds like a parrot? A carrot!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one snowman say to the other snowman? Do you smell carrots?",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "How do you make holy water? You boil the hell out of it!",
    "Why don't eggs tell jokes? Because they'd crack each other up!",
    "What do you call a fake noodle? An impasta!",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call a can opener that doesn't work? A can't opener!"
};